spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/francescomuia/docker-console-config-server.git
          clone-on-start: true
server:
  port: 8888
  
security:
  user: 
    name: root
    password: s3cr3t